# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1095, 797)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 750))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(700, 700))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.loadLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loadLabel.setFont(font)
        self.loadLabel.setObjectName(_fromUtf8("loadLabel"))
        self.verticalLayout_3.addWidget(self.loadLabel)
        self.loadMRIButton = QtGui.QPushButton(self.centralwidget)
        self.loadMRIButton.setEnabled(True)
        self.loadMRIButton.setObjectName(_fromUtf8("loadMRIButton"))
        self.verticalLayout_3.addWidget(self.loadMRIButton)
        self.loadXRayButton = QtGui.QPushButton(self.centralwidget)
        self.loadXRayButton.setObjectName(_fromUtf8("loadXRayButton"))
        self.verticalLayout_3.addWidget(self.loadXRayButton)
        self.loadSTButton = QtGui.QPushButton(self.centralwidget)
        self.loadSTButton.setObjectName(_fromUtf8("loadSTButton"))
        self.verticalLayout_3.addWidget(self.loadSTButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.regitsrationLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regitsrationLabel.sizePolicy().hasHeightForWidth())
        self.regitsrationLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.regitsrationLabel.setFont(font)
        self.regitsrationLabel.setObjectName(_fromUtf8("regitsrationLabel"))
        self.verticalLayout_4.addWidget(self.regitsrationLabel)
        self.rigidRegistrationButton = QtGui.QPushButton(self.centralwidget)
        self.rigidRegistrationButton.setEnabled(True)
        self.rigidRegistrationButton.setObjectName(_fromUtf8("rigidRegistrationButton"))
        self.verticalLayout_4.addWidget(self.rigidRegistrationButton)
        self.articulatedRegistrationButton = QtGui.QPushButton(self.centralwidget)
        self.articulatedRegistrationButton.setObjectName(_fromUtf8("articulatedRegistrationButton"))
        self.verticalLayout_4.addWidget(self.articulatedRegistrationButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.viewLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabel.setFont(font)
        self.viewLabel.setObjectName(_fromUtf8("viewLabel"))
        self.verticalLayout_5.addWidget(self.viewLabel)
        self.xRayCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.xRayCheckBox.setObjectName(_fromUtf8("xRayCheckBox"))
        self.verticalLayout_5.addWidget(self.xRayCheckBox)
        self.stCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.stCheckBox.setObjectName(_fromUtf8("stCheckBox"))
        self.verticalLayout_5.addWidget(self.stCheckBox)
        self.externalLMCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.externalLMCheckBox.setObjectName(_fromUtf8("externalLMCheckBox"))
        self.verticalLayout_5.addWidget(self.externalLMCheckBox)
        self.vertebralLMCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.vertebralLMCheckBox.setObjectName(_fromUtf8("vertebralLMCheckBox"))
        self.verticalLayout_5.addWidget(self.vertebralLMCheckBox)
        spacerItem = QtGui.QSpacerItem(60, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.mriCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.mriCheckBox.setObjectName(_fromUtf8("mriCheckBox"))
        self.verticalLayout_5.addWidget(self.mriCheckBox)
        self.sMRICheckBox = QtGui.QCheckBox(self.centralwidget)
        self.sMRICheckBox.setObjectName(_fromUtf8("sMRICheckBox"))
        self.verticalLayout_5.addWidget(self.sMRICheckBox)
        self.mriVertebraeCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.mriVertebraeCheckBox.setObjectName(_fromUtf8("mriVertebraeCheckBox"))
        self.verticalLayout_5.addWidget(self.mriVertebraeCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.sliceLabel = QtGui.QLabel(self.centralwidget)
        self.sliceLabel.setObjectName(_fromUtf8("sliceLabel"))
        self.verticalLayout_5.addWidget(self.sliceLabel)
        self.sliceSpinBox = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceSpinBox.sizePolicy().hasHeightForWidth())
        self.sliceSpinBox.setSizePolicy(sizePolicy)
        self.sliceSpinBox.setObjectName(_fromUtf8("sliceSpinBox"))
        self.verticalLayout_5.addWidget(self.sliceSpinBox)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.saveLabel = QtGui.QLabel(self.centralwidget)
        self.saveLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveLabel.setFont(font)
        self.saveLabel.setObjectName(_fromUtf8("saveLabel"))
        self.verticalLayout_6.addWidget(self.saveLabel)
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(True)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.verticalLayout_6.addWidget(self.saveButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem3 = QtGui.QSpacerItem(250, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "3DSpineVizualization", None))
        self.loadLabel.setText(_translate("MainWindow", "Load", None))
        self.loadMRIButton.setText(_translate("MainWindow", "Load MRI", None))
        self.loadXRayButton.setText(_translate("MainWindow", "Load X-Ray", None))
        self.loadSTButton.setText(_translate("MainWindow", "Load Surface Topology", None))
        self.regitsrationLabel.setText(_translate("MainWindow", "Registration", None))
        self.rigidRegistrationButton.setText(_translate("MainWindow", "Rigid Registration", None))
        self.articulatedRegistrationButton.setText(_translate("MainWindow", "Articulated Registration", None))
        self.viewLabel.setText(_translate("MainWindow", "View", None))
        self.xRayCheckBox.setText(_translate("MainWindow", "X-Ray", None))
        self.stCheckBox.setText(_translate("MainWindow", "Surface", None))
        self.externalLMCheckBox.setText(_translate("MainWindow", "External Landmarks", None))
        self.vertebralLMCheckBox.setText(_translate("MainWindow", "Vertebral Landmarks", None))
        self.mriCheckBox.setText(_translate("MainWindow", "MRI", None))
        self.sMRICheckBox.setText(_translate("MainWindow", "Saggital MRIs", None))
        self.mriVertebraeCheckBox.setText(_translate("MainWindow", "MRI vertebrae", None))
        self.sliceLabel.setText(_translate("MainWindow", "View registered slice", None))
        self.saveLabel.setText(_translate("MainWindow", "Save Registered File", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

